export const BACKEND_URL = "http://localhost:8000";
export const TOTAL_SELECTED_QUESTION = "TOTAL_SELECTED_QUESTIONS";
export const CURRENT_QUESTION = "CURRENT_QUESTION";
export const CURRENT_SELECTED_PACKAGE = "CURRENT_SELECTED_PACKAGE";
